const apps = [
  ['Canvas', 'Palle Studio', 'Free', '✦', 'violet', 'Design'], ['Focus Flow', 'Ambit Labs', '$4.99', '◒', 'orange', 'Productivity'], ['Serein', 'Northwind', 'Free', '☾', 'blue', 'Wellness'], ['Pace', 'Paceworks', '$2.99', '↗', 'green', 'Health'], ['Type Foundry', 'Kite & Co.', '$8.99', 'T', 'pink', 'Design'], ['Pocket Planet', 'Orbital', 'Free', '◉', 'teal', 'Education']
]
const mark = '<div class="mark small" aria-label="MyApp logo"><span>Λ</span></div>'
document.querySelector('#root').innerHTML = `<main><header class="topbar"><a class="brand" href="#top">${mark}<span>AURA</span><b>STORE</b></a><nav>${['Discover','Categories','Collections'].map((item, i) => `<button class="${i === 0 ? 'selected' : ''}" data-nav>${item}</button>`).join('')}</nav><div class="header-actions"><button class="theme-toggle" aria-label="Toggle color theme"><span>☾</span><i></i></button><button class="avatar" aria-label="Account">AS</button></div></header><section class="hero" id="top"><div class="hero-copy"><p class="eyebrow">A CURATED DIGITAL MARKETPLACE</p><h1>Great apps,<br><em>beautifully</em> found.</h1><p class="intro">Thoughtful tools for your work, wonder, and every day in between.</p><a class="primary" href="#trending">Explore this week <span>→</span></a></div><div class="hero-art" aria-hidden="true"><div class="orb orb-one"></div><div class="orb orb-two"></div><div class="orbit"></div><div class="floating-card"><div class="flower">✣</div><div><small>EDITOR'S PICK</small><strong>Canvas</strong><span>Make space for ideas.</span></div></div></div></section><section class="discover" id="trending"><div class="section-heading"><div><p class="eyebrow">THIS WEEK</p><h2>Trending now</h2></div><a href="#all-apps">See all <span>→</span></a></div><div class="feature-grid"><article class="feature feature-waves"><div class="feature-content"><span class="pill">Productivity</span><h3>Find your<br>flow state.</h3><p>Small rituals for deeper work.</p><button data-open="Focus Flow">Meet Focus Flow <span>→</span></button></div><div class="wave-symbol">◒</div></article><article class="feature feature-serein"><div class="feature-content"><span class="pill">Wellness</span><h3>A quieter corner<br>of the internet.</h3><p>Unwind, one breath at a time.</p><button data-open="Serein">Discover Serein <span>→</span></button></div><div class="moon-symbol">☾</div></article></div></section><section class="library" id="all-apps"><div class="library-head"><div><p class="eyebrow">FRESH FINDS</p><h2>Made to keep</h2></div><label class="search"><span>⌕</span><input id="search" placeholder="Search the store" aria-label="Search apps"></label></div><div class="apps-grid" id="app-grid"></div><p class="empty" hidden></p></section><footer><a class="brand" href="#top">${mark}<span>AURA</span><b>STORE</b></a><p>Curated with care, for a more considered digital life.</p><div><a href="#top">About</a><a href="#top">Support</a><a href="#top">Privacy</a></div></footer><div class="toast" hidden></div></main>`

const grid = document.querySelector('#app-grid'), empty = document.querySelector('.empty'), toast = document.querySelector('.toast')
document.querySelectorAll('.brand span').forEach(label => { label.textContent = 'MYAPP' })
document.querySelectorAll('.brand b').forEach(label => { label.textContent = 'APP STORE' })
document.querySelector('.avatar').textContent = 'MA'
document.querySelector('.hero .eyebrow').textContent = 'THE MYAPP APP STORE'
document.head.insertAdjacentHTML('beforeend', '<style>.get{background:#087cf0!important;border-color:#087cf0!important;color:#fff!important;box-shadow:0 2px 7px #087cf045}.get:hover{background:#0069d4!important;border-color:#0069d4!important}.get.saved{background:transparent!important;border-color:var(--line)!important;color:var(--ink)!important;box-shadow:none}</style>')
let saved = [], toastTimer
function notify(message) { toast.textContent = message; toast.hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => { toast.hidden = true }, 2200) }
function render(query = '') { const result = apps.filter(app => app.join(' ').toLowerCase().includes(query.toLowerCase())); grid.innerHTML = result.map(([name, maker, price, icon, tone, tag]) => `<article class="app-card"><div class="app-icon ${tone}">${icon}</div><div class="app-info"><h3>${name}</h3><p>${maker}</p><span>${tag}</span></div><button class="get ${saved.includes(name) ? 'saved' : ''}" data-save="${name}">${saved.includes(name) ? 'Saved' : price}</button></article>`).join(''); empty.hidden = Boolean(result.length); empty.textContent = `No apps match “${query}”. Try another search.` }
render()
document.querySelector('.theme-toggle').addEventListener('click', () => { const dark = document.documentElement.dataset.theme !== 'dark'; document.documentElement.dataset.theme = dark ? 'dark' : 'light'; document.querySelector('.theme-toggle span').textContent = dark ? '☼' : '☾' })
document.querySelectorAll('[data-nav]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-nav]').forEach(item => item.classList.remove('selected')); button.classList.add('selected') }))
document.querySelector('#search').addEventListener('input', event => render(event.target.value))
grid.addEventListener('click', event => { const name = event.target.dataset.save; if (!name) return; const exists = saved.includes(name); saved = exists ? saved.filter(item => item !== name) : [...saved, name]; render(document.querySelector('#search').value); notify(exists ? `${name} removed from your library` : `${name} added to your library`) })
document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => notify(`${button.dataset.open} opened`)))
